<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="DESKTOP-8VF1PVM" failures="1" tests="7" name="Default test(failed)(failed)" time="0.078" errors="0" timestamp="2022-10-28T12:33:27 IST">
  <testcase classname="com.failedtestcase.FailedTest1" name="test" time="0.011">
    <skipped/>
  </testcase> <!-- test -->
  <testcase classname="com.failedtestcase.FailedTest1" name="test" time="0.002">
    <skipped/>
  </testcase> <!-- test -->
  <testcase classname="com.failedtestcase.FailedTest1" name="test" time="0.002">
    <skipped/>
  </testcase> <!-- test -->
  <testcase classname="com.failedtestcase.FailedTest1" name="test" time="0.002">
    <skipped/>
  </testcase> <!-- test -->
  <testcase classname="com.failedtestcase.FailedTest1" name="test" time="0.002">
    <skipped/>
  </testcase> <!-- test -->
  <testcase classname="com.failedtestcase.FailedTest1" name="test" time="0.001">
    <skipped/>
  </testcase> <!-- test -->
  <testcase classname="com.failedtestcase.FailedTest1" name="test" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [A] but found [a]">
      <![CDATA[java.lang.AssertionError: expected [A] but found [a]
at com.failedtestcase.FailedTest1.test(FailedTest1.java:11)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- test -->
  <testcase classname="com.failedtestcase.FailedTest1" name="test3" time="0.0">
    <ignored/>
  </testcase> <!-- test3 -->
  <testcase classname="com.failedtestcase.FailedTest1" name="test2" time="0.0">
    <ignored/>
  </testcase> <!-- test2 -->
</testsuite> <!-- Default test(failed)(failed) -->
